fcm:
  config-path: firebase/test-e93e5-firebase-adminsdk-fbsvc-e966fa8ac8.json
  
toss:
  test-secret-key: "test_sk_DLJOpm5QrlPZomDq49DLrPNdxbWn"  # 테스트 Secret Key
  success-url: "http://localhost:5173/kiosk/paymentSuccess"
  fail-url: "http://localhost:5173/kiosk/paymentFail"  